"""Harness-owned question, optional focus, search phrases and prior graph candidate."""
import json

from lfx.io import DropdownInput, HandleInput, Output, StrInput
from lfx.schema import Data

from nima_semantica.component_contracts import manifest_for_component
from nima_semantica.deep_research_passes import PassResearchRequest
from nima_semantica.orchestration.langflow.adapter_support import native
from nima_semantica.orchestration.langflow.stages.base import RequestFields as BaseComponent
from nima_semantica.providers import strict_json_object


class DeepResearchPassFields(BaseComponent):
    name = "DeepResearchPassFields"
    display_name = "Deep Research · Question and Focus"
    description = "The harness supplies the original research question and optionally a prior review-graph artifact plus a focus question. Short first-pass phrases may be supplied; absent phrases are generated by the bounded planner. No public field grants provider/model/write authority."
    nima_manifest = manifest_for_component("DeepResearchPassFields")
    inputs = [DropdownInput(name="mode", display_name="Mode", options=["preview", "research"], value="preview"),
        StrInput(name="operation_id", display_name="Unique attempt ID", value=""),
        StrInput(name="run_id", display_name="Harness run ID", value=""),
        StrInput(name="questions_json", display_name="Original research questions (JSON list)", value="[]"),
        StrInput(name="graph_revision_json", display_name="Exact project graph revision (JSON)", value="null"),
        StrInput(name="search_phrases_json", display_name="Optional short first-pass phrases (JSON list)", value="[]"),
        StrInput(name="input_graph_artifact_id", display_name="Optional prior review-graph artifact ID", value=""),
        StrInput(name="focus_question", display_name="Optional continuation focus question", value=""),
        HandleInput(name="mcp_request", display_name="Optional typed request JSON", input_types=["Message", "Data", "JSON"], required=False)]
    outputs = [Output(name="request", display_name="Validated pass request", method="request_data", group_outputs=True),
        Output(name="preview", display_name="Request preview", method="preview_message", group_outputs=True)]

    async def run(self):
        override = native(getattr(self, "mcp_request", None))
        if isinstance(override, str):
            if len(override) > 150_000:
                raise ValueError("request exceeds input limit")
            override = strict_json_object(override) if override.strip() else {}
        if override is None:
            override = {}
        if not isinstance(override, dict):
            raise ValueError("expected request object")
        research = {"mode": self.mode, "operation_id": self.operation_id or None,
            "run_id": self.run_id or None, "questions": json.loads(self.questions_json),
            "graph_revision": json.loads(self.graph_revision_json)}
        payload = {"research": research, "search_phrases": json.loads(self.search_phrases_json),
            "input_graph_artifact_id": self.input_graph_artifact_id or None,
            "focus_question": self.focus_question or None}
        return PassResearchRequest.model_validate(payload | override).model_dump(mode="json")

    async def request_data(self) -> Data:
        return await self.result_data()
